SchoolarishpManagement/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolarshipManagement.DataAccess.IRepository;
using SchoolarshipManagement.Models.Models;
using SchoolarshipManagement.Models.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolarshipManagement.Controllers
{
    public class CityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CityController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            CityVM cityVM = new CityVM()
            {
                City = new City(),
                CountryList = _unitOfWork.CountryRepository.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            cityVM.City = _unitOfWork.CityRepository.Get(id);
            if (cityVM.City == null)
            {
                return NotFound();
            }
            return View(cityVM);
        }

        public IActionResult Upsert(int? id)
        {
            CityVM cityVM = new CityVM()
            {
                City = new City(),               
                CountryList = _unitOfWork.CountryRepository.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            if (id == null)
            {
                //this is for create
                return View(cityVM);
            }
            //this is for edit
            cityVM.City = _unitOfWork.CityRepository.Get(id.GetValueOrDefault());
            if (cityVM.City == null)
            {
                return NotFound();
            }
            return View(cityVM);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(CityVM cityVM)
        {
            if (ModelState.IsValid)
            { 
                if (cityVM.City.Id == 0)
                {
                    _unitOfWork.CityRepository.Add(cityVM.City);
                }
                else
                {
                    _unitOfWork.CityRepository.Update(cityVM.City);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            else
            {                
                cityVM.CountryList = _unitOfWork.CountryRepository.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
               
                if (cityVM.City.Id != 0)
                {
                    cityVM.City = _unitOfWork.CityRepository.Get(cityVM.City.Id);
                }
            }
            return View(cityVM);
        }



        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.CityRepository.GetAll(includeProperties: "Country");
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.CityRepository.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.CityRepository.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

SchoolarishpManagement/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolarshipManagement.DataAccess.IRepository;
using SchoolarshipManagement.Models.Models;
using SchoolarshipManagement.Models.ViewModels;

namespace SchoolarshipManagement.Controllers
{
    public class CourseController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CourseController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            Course course = new Course();
            course = _unitOfWork.CourseRepository.Get(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        public IActionResult Upsert(int? id)
        {
            Course course = new Course();
            if (id == null)
            {
                //this is for create
                return View(course);
            }
           
            //this is for edit
            course = _unitOfWork.CourseRepository.Get(id.GetValueOrDefault());
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Course course)
        {
            if (ModelState.IsValid)
            {
                if (course.Id == 0)
                {
                    _unitOfWork.CourseRepository.Add(course);
                }
                else
                {
                    _unitOfWork.CourseRepository.Update(course);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.CourseRepository.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.CourseRepository.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.CourseRepository.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

SchoolarishpManagement/Controllers/GenderController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolarshipManagement.DataAccess.IRepository;
using SchoolarshipManagement.Models.Models;

namespace SchoolarshipManagement.Controllers
{
    public class GenderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public GenderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            Gender gender = new Gender();
            gender = _unitOfWork.GenderRepository.Get(id);
            if (gender == null)
            {
                return NotFound();
            }
            return View(gender);
        }

        public IActionResult Upsert(int? id)
        {
            Gender gender = new Gender();
            if (id == null)
            {
                //this is for create
                return View(gender);
            }
           
            //this is for edit
            gender = _unitOfWork.GenderRepository.Get(id.GetValueOrDefault());
            if (gender == null)
            {
                return NotFound();
            }
            return View(gender);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Gender gender)
        {
            if (ModelState.IsValid)
            {
                if (gender.Id == 0)
                {
                    _unitOfWork.GenderRepository.Add(gender);
                }
                else
                {
                    _unitOfWork.GenderRepository.Update(gender);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(gender);
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.GenderRepository.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.GenderRepository.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.GenderRepository.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

SchoolarishpManagement/Controllers/LevelController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolarshipManagement.DataAccess.IRepository;
using SchoolarshipManagement.Models.Models;
using SchoolarshipManagement.Models.ViewModels;

namespace SchoolarshipManagement.Controllers
{
    public class LevelController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public LevelController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            Level level = new Level();
            level = _unitOfWork.LevelRepository.Get(id);
            if (level == null)
            {
                return NotFound();
            }
            return View(level);
        }

        public IActionResult Upsert(int? id)
        {
            Level level = new Level();
            if (id == null)
            {
                //this is for create
                return View(level);
            }
            
            //this is for edit
            level = _unitOfWork.LevelRepository.Get(id.GetValueOrDefault());
            if (level == null)
            {
                return NotFound();
            }
            return View(level);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Level level)
        {
            if (ModelState.IsValid)
            {
                if (level.Id == 0)
                {
                    _unitOfWork.LevelRepository.Add(level);
                }
                else
                {
                    _unitOfWork.LevelRepository.Update(level);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(level);
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.LevelRepository.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.LevelRepository.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.LevelRepository.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

SchoolarishpManagement/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Back to List</a>
    </div>
</div>

SchoolarishpManagement/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Details</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Back to List</a>
    </div>
</div>

SchoolarishpManagement/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Back to List</a>
    </div>
</div>

SchoolarishpManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schoolarishp Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Schoolarishp Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Students
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Gender" asp-action="Index">Gender / Sexe </a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Country" asp-action="Index">Countries</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="City" asp-action="Index">City</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Courses
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Filiere" asp-action="Index">Filieres</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Country" asp-action="Index">Countries</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="City" asp-action="Index">City</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Registrations
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Level" asp-action="Index">Levels</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="AcademicYear" asp-action="Index">Academic Years</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Country" asp-action="Index">Registrations</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="City" asp-action="Index">City</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications">
                @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50 bg-primary">
        <div class="container">
            &copy; 2020 - Schoolarishp Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SchoolarishpManagement/Views/Shared/_Notifications.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["Success"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
else
{
    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            @TempData["Error"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}